# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
  projectName: 'forgedinthelore-net'
 

stages:
- stage: Test
  jobs:
    - job: Setup
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/$(projectName)*.csproj'
          displayName: 'Restore Nuget Packages'
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'oibss-f'
            scannerMode: 'MSBuild'
            projectKey: 'OIBSS-F_Forged-In-The-Lore'
            projectName: 'Forged In The Lore'
    - job: UnitTest
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/$(projectName)*.csproj'
            arguments: '--no-restore'
          displayName: 'Build projects'
          
        - task: SonarCloudAnalyze@1
        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/*-test.csproj'
            arguments: '--no-restore --no-build'
          displayName: 'Run Tests'
    - job: Integration
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/*-inttest.csproj'
            arguments: '--no-restore --no-build'
          displayName: 'Run Tests'

    - job: Deliver
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker-hub'
            repository: 'davidhellinga/forgedinthelore'
            command: 'buildAndPush'
            Dockerfile: '**/forgedinthelore/Dockerfile'