# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
  projectName: 'forgedinthelore-net'
 
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/$(projectName)*.csproj'
  displayName: 'Restore Nuget Packages'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '98f6bfac-72f0-4905-84da-7df248701b55'
    definition: '14'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)/forgedinthelore-net/wwwroot'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Pipeline.Workspace)/forgedinthelore-net/wwwroot/*.zip'
    destinationFolder: '$(Pipeline.Workspace)/forgedinthelore-net/wwwroot'
    cleanDestinationFolder: true
    overwriteExistingFiles: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/$(projectName)*.csproj'
    arguments: '--no-restore'
  displayName: 'Build projects'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
    arguments: '--no-restore --no-build'
  displayName: 'Run Tests'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/$(projectName)*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    modifyOutputPath: false
  displayName: 'Publish Forged in the Lore'